### ISSUE TITLE
Refactor: Investigate outputting an AST rather than HTML

### ISSUE THREAD

**Issue by ben-eb** [ben-eb/midas#4]
Leaving this here for a reference, it's low down on my priority list for now.

I'm considering making this module output something that is more compatible with React, and other consumers, which work best with a node tree instead of setting HTML dangerously.

We can do this by using https://github.com/wooorm/hastscript and https://github.com/Matt-Esch/virtual-dom/tree/master/virtual-hyperscript. Also, we can use https://github.com/wooorm/hast-util-to-html to keep a HTML output, but not make it the default. Finally, we can use https://github.com/wooorm/hast-to-hyperscript to transform the HAST tree to another output.

Help welcome if you have any experience in this area. 😄

**Comment by wooorm** [comment]
Cool! I believe it won’t be very hard, there are few places where HTML is actually built, and most are already done in a manner similar to virtual dom creation (e.g., [`span()`](https://github.com/ben-eb/midas/blob/33a0da2f01c8dd7c954b8aa9f3edf1603d62d109/src/stringifier.js#L26)).

Creating elements is pretty standardised between the hyperscript syntaxes, but there are big differences in how classes are handled: `hyperscript` must have them in the tag-name (`span.midas-foo`), `virtual-dom/h` / `hastscript` allows that too, but `React.createElement` doesn’t.  On the other hand, `React.createElement`, `virtual-dom/h`, and `hastscript` all allow a `className` property in the `props` object (`hyperscript` doesn’t).

You can either allow user’s to pass in their own `h()`, and mention `hyperscript` isn’t properly supported (they should do that conversion themselves if they want it), or go the whole way with `hastscript` / `hast-util-to-hyperscript`.

And, next to that, `hast-util-to-html` has the best conversion to HTML to my knowledge, so using that to still provide support for compiled HTML gets a :+1: from me.

**Comment by ben-eb** [comment]
Addressed in https://github.com/ben-eb/midas/commit/a79024557099e07f09d2df69c6cbeb11da88327d.
